#!/bin/bash

# PORT SCANNING
#
# YOU CAN SEE PORTS AS VIRTUAL CHANNELS WHERE PROGRAM CAN
# COMUNICATE.
# EXAMPLES ARE TCP/80 HTTP TCP/443 HTTPS FOR TCP PACKETS
# AND UDP/53 DOMAIN OR UDP/22 SSH FOR UDP PACKETS
#
# THE TCP/UDP PACKETS JUST ADD AN HEADER WITH
# SOURCE/DESTINATION IP AND SOURCE/DESTINATION PORT.
#
# YOU CAN READ THE nmap-services FILE TO FIND MORE:


echo '[*] You can see all the TCP/UDP Port used';
echo '[*] They are locate in the "nmap-services" file';
echo '[*] Example: find /usr/share/nmap -name "nmap-services"';
find /usr/share/nmap -name "nmap-services" 2> /dev/null;
sleep 2s;
echo -e "\n\n";



# YOU CAN SEE YOUR PORT RANGE IN "ip_local_port_range" (LINUX)

echo '[*] You can see your PORT RANGE!!';
echo '[*] It is locate in "ip_local_port_range" file';
echo "[*] Look at /proc/sys/net/ipv4/ip_local_port_range";
echo '[*] Example: find /proc/sys/net/ipv4/ -name "ip_local_port_range"';
find /proc/sys/net/ipv4/ -name "ip_local_port_range" 2> /dev/null;
echo '[*] Example: cat /proc/sys/net/ipv4/ip_local_port_range';
echo '[*] (PS: YOU CAN MODIFY THIS RANGE!!!)';
cat /proc/sys/net/ipv4/ip_local_port_range;
sleep 2s;
echo -e "\n\n";



# THE IANA (INTERNET ASSIGNED NUMBER AUTHORITY)
# HAS THEIR OWN PORT CLASSIFICATION SCHEME,
# DIVIDES IN THREE CATEGORY:
#
# https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml
#
# FIRST CATEGORY: WELL-KNOWN PORTS (0-1023)
# RESERVED PORT FOR WELL-KNOWN SERVICES, AS HTTP/S OR SSH.
# 
# SECOND CATEGORY: REGISTERED PORTS (1024-49151)
# THE PORTS ARE LESS KNOWN THAN WELL-KNOWN PORTS,
# THE MAIN DIFFERENCE IS THAT UNPRIVILEGED USERS CAN
# BIND TO THESE PORTS AND RUN THE SERVICE
# IN THEIR REGISTERED PORT
#
# THIRD CATEGORY: DYNAMIC AND/OR PRIVATE (45152-65535)
# THE IANA REVERVES THIS PORTS FOR DYNAMIC USES.
# E.G. IF YOU SET PORT 0, MOST OS WILL ALLOCATE ONE OF
# THIS PORTS: IT MEAN "CHOOSE AN OPEN PORT"

###########################################################

# COMMON PORTS: TCP
# 
# 21/FTP				FILE TRANSFER PROTOCOL (INSECURE)
# 22/SSH				SECURE SHELL (REMOTE SESSION, SECURE)
# 23/TELNET				TELNET (REMOTE SESSION, INSECURE)
# 25/SMTP				STANDARM MAIL TRANSFER PROTOCOL (INSECURE)
# 53/DOMAIN				DOMAIN NAME SYSTEM (DNS) (INSECURE)
# 80/HTTP 				HTTP (INSECURE)
# 110/POP3				POST OFFICE PROTOCOL 3 FOR EMAIL RETRIEVAL (INSECURE)
# 111/RPCBIND			MAPS SUNRPC PROGRAM NUMBERS TO THEIR TCP/UDP PORT NUMBERS
# 135/MSRPC				MICROSOFT REMOTE PROCEDURE CALL
# 139/NETBIOS-SSN		NETBIOS SESSION SERVICE (WITH MS WINDOWS SERVICES) FILE/PRINTER SHARING
# 143/IMAP				INTERNET MESSAGE ACCESS PROTOCOL 2 (EMAIL, INSECURE)
# 443/HTTPS 			SSL ENCRYPTED HTTP (SECURE)
# 445/MICROSOFT-DS		SMB COMMUNICATION OVER IP (WITH MS WINDOWS SERVICES) FILE/PRINTER SHARING
# 993/IMAPS				IMAP2 WITH SSL (SECURE)
# 995/POP3S				POP3 WITH SSL (SECURE)
# 1723/PPTP				POINT-TO-POINT TUNNELING PROTOCOL (FOR VPN, SOMETIMES REQUIERED FOR ISPs BROADBAND CONNECTIONS)
# 3306/MYSQL			MYSQL DATABASE
# 3389/MS-TERM-SERVER	MICROSOFT TERMINAL SERVICES ADMINISTRATION
# 5900/VNC				VIRTUAL NETWORK COMPUTING (DESKTOP SHARING, INSECURE)
# 8080/HTTP-PROXY		HTTP PROXIES (OR ALTERNATIVE TO 80 PORT)

echo '[*] Example Scan: Common TCP Ports ';
echo '[*] Scanning: nmap -PS21,22,23,25,110,111,135,139,143,443,445,993,995,1723,3306,3389,5900,8080 -PA80,443 192.168.1.1';
nmap -PS21,22,23,25,110,111,135,139,143,443,445,993,995,1723,3306,3389,5900,8080 -PA80,443 192.168.1.1;
sleep 2s;
echo -e "\n\n";



# COMMON PORTS: UDP
#
# 53/DOMAIN				DOMAIN NAME SYSTEM (DNS) (INSECURE)
# 67/DHCPS				DYNAMIC HOST CONFIGURATION PROTOCOL SERVER (GIVES IP ADDRESS TO HOSTS)
# 68/DHCPC				DHCP CLIENT
# 69/TFTP				TRIVIAL FILE TRANSFER PROTOCOL
# 123/NTP				NETWORK TIME PROTOCOL
# 135/MSRPC				MICROSOFT REMOTE PROCEDURE CALL
# 137/NETBIOS-NS 		NETBIOS NAME SERVICE
# 138/NETBIOS-DGM		NETBIOS DATAGRAM SERVICE
# 139/NETBIOS-SSN		NETBIOS SESSION SERVICE (WITH MS WINDOWS SERVICES) FILE/PRINTER SHARING
# 161/SNMP 				SIMPLE NETWORK MANAGEMENT PROTOCOL
# 162/SNMPTRAP			SNMP TRAP (AB SMTP AGENT USES 161 AND A SMTP MANAGER USES 162)
# 445/MICROSOFT-DS		SMB COMMUNICATION OVER IP (WITH MS WINDOWS SERVICES) FILE/PRINTER SHARING
# 500/ISAKMP			INTERNET SECURITY ASSOCIATION AND KEY MANAGEMENT PROTOCOL (TO SETUP VPN IPSEC ETC.)
# 514/SYSLOG			STANDARD UNIX LOG DAEMON
# 520/RIP 				ROUTING INFORMATION PROTOCOL
# 631/IPP 				INTERNET PRINT PROTOCOL
# 1434/MS-SQL-DS		MICROSOFT SQL SERVER
# 1900/UPNP				MICROSOFT SIMPLE DEVICE DISCOVERY PROTOCOL (DISCOVERY OF UNIVERSAL PLUG-AND-PLAY DEVICES)
# 4500/NAT-T-IKE		NEGOTIATING NETWORK ADDRESS TRANSLATION TRASVERSAL WHILE INITIATING IPSEC CONNECTION (USING INTERNET KEY EXCHANGE)
# 49152/UNKNOWN			FIRST OF DYNAMIC/PRIVATE PORTS

echo '[*] Example Scan: Common UDP Ports ';
echo '[*] Scanning: nmap -PU53,67-69,123,135,137-139,161,162,445,500,514,520,631,1434,1900,4500,49152 192.168.1.1';
nmap -PU53,67-69,123,135,137-139,161,162,445,500,514,520,631,1434,1900,4500,49152 192.168.1.1;
sleep 2s;
echo -e "\n\n";